/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --env-interface=CloudflareEnv cloudflare-env.d.ts` (hash: 8677634dc29d7fc7bc07db698ffd83c0)
interface __BaseEnv_CloudflareEnv {
	NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
	CARD_ASSETS_BUCKET: R2Bucket;
	ASSETS: Fetcher;
	NEXT_PUBLIC_SITE_URL: "https://mewtrucard.com/" | "https://mewtrucard-preview.auroroa.workers.dev/";
	AUTH_URL: "https://mewtrucard.com/" | "https://mewtrucard-preview.auroroa.workers.dev/";
	DATABASE_URL: string;
	DIRECT_URL: string;
	X_AI_API_KEY: string;
	R2_SECRET_ACCESS_KEY: string;
	R2_ACCESS_KEY_ID: string;
	NEXTAUTH_URL: string;
	NEXTAUTH_SECRET: string;
	AUTH_GOOGLE_SECRET: string;
	AUTH_GOOGLE_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	GOOGLE_CLIENT_ID: string;
	SPOTIFY_CLIENT_SECRET: string;
	SPOTIFY_CLIENT_ID: string;
	R2_BUCKET_NAME: string;
	R2_ACCOUNT_ID: string;
	CF_ACCOUNT_ID: string;
	CF_API_TOKEN: string;
	CF_HASH_CODE: string;
	POSTGRES_URL: string;
	NEXT_PUBLIC_BASE_URL: string;
	PUBLIC_WEBSITE_URL: string;
	OPENROUTER_API_KEY: string;
	DEEPSEEK_API_KEY: string;
	GEMINI_API_KEY: string;
	KIE_API_KEY: string;
	HOLD_AI_KEY: string;
	HOLD_AI_BASE_URL: string;
	NEXT_PUBLIC_ADSENSE_SLOT_GENERATION: string;
	CLOUDINARY_CLOUD_NAME: string;
	CLOUDINARY_API_KEY: string;
	CLOUDINARY_API_SECRET: string;
	CLOUDINARY_UPLOAD_PRESET: string;
	STRIPE_SECRET_KEY: string;
	STRIPE_PUBLISHABLE_KEY: string;
	STRIPE_WEBHOOK_SECRET: string;
	STRIPE_MONTHLY_PRICE_ID: string;
	STRIPE_YEARLY_PRICE_ID: string;
	ENDPOINT: string;
	HM_API_KEY: string;
	HM_BASE_URL: string;
	WORKER_SELF_REFERENCE: Fetcher /* mewtrucard */ | Service<typeof import("./.open-next/worker").default>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface ProductionEnv {
		NEXT_INC_CACHE_R2_BUCKET: R2Bucket;
		CARD_ASSETS_BUCKET: R2Bucket;
		ASSETS: Fetcher;
		NEXT_PUBLIC_SITE_URL: "https://mewtrucard.com/";
		AUTH_URL: "https://mewtrucard.com/";
		DATABASE_URL: string;
		DIRECT_URL: string;
		X_AI_API_KEY: string;
		R2_SECRET_ACCESS_KEY: string;
		R2_ACCESS_KEY_ID: string;
		NEXTAUTH_URL: string;
		NEXTAUTH_SECRET: string;
		AUTH_GOOGLE_SECRET: string;
		AUTH_GOOGLE_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		GOOGLE_CLIENT_ID: string;
		SPOTIFY_CLIENT_SECRET: string;
		SPOTIFY_CLIENT_ID: string;
		R2_BUCKET_NAME: string;
		R2_ACCOUNT_ID: string;
		CF_ACCOUNT_ID: string;
		CF_API_TOKEN: string;
		CF_HASH_CODE: string;
		POSTGRES_URL: string;
		NEXT_PUBLIC_BASE_URL: string;
		PUBLIC_WEBSITE_URL: string;
		OPENROUTER_API_KEY: string;
		DEEPSEEK_API_KEY: string;
		GEMINI_API_KEY: string;
		KIE_API_KEY: string;
		HOLD_AI_KEY: string;
		HOLD_AI_BASE_URL: string;
		NEXT_PUBLIC_ADSENSE_SLOT_GENERATION: string;
		CLOUDINARY_CLOUD_NAME: string;
		CLOUDINARY_API_KEY: string;
		CLOUDINARY_API_SECRET: string;
		CLOUDINARY_UPLOAD_PRESET: string;
		STRIPE_SECRET_KEY: string;
		STRIPE_PUBLISHABLE_KEY: string;
		STRIPE_WEBHOOK_SECRET: string;
		STRIPE_MONTHLY_PRICE_ID: string;
		STRIPE_YEARLY_PRICE_ID: string;
		ENDPOINT: string;
		HM_API_KEY: string;
		HM_BASE_URL: string;
		WORKER_SELF_REFERENCE: Fetcher /* mewtrucard */;
	}
	interface Env extends __BaseEnv_CloudflareEnv {}
}
interface CloudflareEnv extends __BaseEnv_CloudflareEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXT_PUBLIC_SITE_URL" | "AUTH_URL" | "DATABASE_URL" | "DIRECT_URL" | "X_AI_API_KEY" | "R2_SECRET_ACCESS_KEY" | "R2_ACCESS_KEY_ID" | "NEXTAUTH_URL" | "NEXTAUTH_SECRET" | "AUTH_GOOGLE_SECRET" | "AUTH_GOOGLE_ID" | "GOOGLE_CLIENT_SECRET" | "GOOGLE_CLIENT_ID" | "SPOTIFY_CLIENT_SECRET" | "SPOTIFY_CLIENT_ID" | "R2_BUCKET_NAME" | "R2_ACCOUNT_ID" | "CF_ACCOUNT_ID" | "CF_API_TOKEN" | "CF_HASH_CODE" | "POSTGRES_URL" | "NEXT_PUBLIC_BASE_URL" | "PUBLIC_WEBSITE_URL" | "OPENROUTER_API_KEY" | "DEEPSEEK_API_KEY" | "GEMINI_API_KEY" | "KIE_API_KEY" | "HOLD_AI_KEY" | "HOLD_AI_BASE_URL" | "NEXT_PUBLIC_ADSENSE_SLOT_GENERATION" | "CLOUDINARY_CLOUD_NAME" | "CLOUDINARY_API_KEY" | "CLOUDINARY_API_SECRET" | "CLOUDINARY_UPLOAD_PRESET" | "STRIPE_SECRET_KEY" | "STRIPE_PUBLISHABLE_KEY" | "STRIPE_WEBHOOK_SECRET" | "STRIPE_MONTHLY_PRICE_ID" | "STRIPE_YEARLY_PRICE_ID" | "ENDPOINT" | "HM_API_KEY" | "HM_BASE_URL">> {}
}
